/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculadora;

import java.awt.event.ActionListener;
import javax.script.ScriptEngineManager;

/**
 *
 * @author joaoc
 */
public class TelaCalculadora extends javax.swing.JFrame {

    
    ScriptEngineManager sm = new ScriptEngineManager();
    Calcular c = new Calcular();

    /**
     * Creates new form TelaCalculadora
     */
    public TelaCalculadora() {
        initComponents();
        setLocationRelativeTo(null);      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jtxt_resultado = new javax.swing.JTextField();
        jbt_8 = new javax.swing.JButton();
        jbt_09 = new javax.swing.JButton();
        jbt_divisao = new javax.swing.JButton();
        jbt_07 = new javax.swing.JButton();
        jbt_05 = new javax.swing.JButton();
        jbt_06 = new javax.swing.JButton();
        jbt_multiplicacao = new javax.swing.JButton();
        jbt_04 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jbt_subtrair = new javax.swing.JButton();
        jbt_01 = new javax.swing.JButton();
        jbt_00 = new javax.swing.JButton();
        jbt_resultado = new javax.swing.JButton();
        jbt_somar = new javax.swing.JButton();
        jbt_limpar = new javax.swing.JButton();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CALCULADORA");

        jtxt_resultado.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jtxt_resultado.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxt_resultado.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jtxt_resultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_resultadoActionPerformed(evt);
            }
        });

        jbt_8.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jbt_8.setText("8");
        jbt_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_8ActionPerformed(evt);
            }
        });

        jbt_09.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jbt_09.setText("9");
        jbt_09.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_09ActionPerformed(evt);
            }
        });

        jbt_divisao.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jbt_divisao.setText("/");
        jbt_divisao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_divisaoActionPerformed(evt);
            }
        });

        jbt_07.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jbt_07.setText("7");
        jbt_07.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_07ActionPerformed(evt);
            }
        });

        jbt_05.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jbt_05.setText("5");
        jbt_05.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_05ActionPerformed(evt);
            }
        });

        jbt_06.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jbt_06.setText("6");
        jbt_06.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_06ActionPerformed(evt);
            }
        });

        jbt_multiplicacao.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jbt_multiplicacao.setText("x");
        jbt_multiplicacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_multiplicacaoActionPerformed(evt);
            }
        });

        jbt_04.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jbt_04.setText("4");
        jbt_04.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_04ActionPerformed(evt);
            }
        });

        jButton11.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton11.setText("2");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton12.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton12.setText("3");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jbt_subtrair.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jbt_subtrair.setText("-");
        jbt_subtrair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_subtrairActionPerformed(evt);
            }
        });

        jbt_01.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jbt_01.setText("1");
        jbt_01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_01ActionPerformed(evt);
            }
        });

        jbt_00.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jbt_00.setText("0");
        jbt_00.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_00ActionPerformed(evt);
            }
        });

        jbt_resultado.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jbt_resultado.setText("=");
        jbt_resultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_resultadoActionPerformed(evt);
            }
        });

        jbt_somar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jbt_somar.setText("+");
        jbt_somar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_somarActionPerformed(evt);
            }
        });

        jbt_limpar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jbt_limpar.setText("AC");
        jbt_limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_limparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxt_resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jbt_01, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jbt_subtrair, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jbt_limpar, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jbt_00, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jbt_resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jbt_somar, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jbt_07, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jbt_04, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jbt_05, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jbt_06, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jbt_multiplicacao, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jbt_8, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jbt_09, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jbt_divisao, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jtxt_resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbt_8, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbt_09, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbt_divisao, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbt_07, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbt_05, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbt_06, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbt_multiplicacao, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbt_04, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbt_subtrair, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbt_01, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbt_00, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbt_resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbt_somar, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbt_limpar, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbt_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_8ActionPerformed
        c.digiteNumero(8);
        jtxt_resultado.setText(c.getValores());
    }//GEN-LAST:event_jbt_8ActionPerformed

    private void jbt_05ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_05ActionPerformed
        c.digiteNumero(5);
        jtxt_resultado.setText(c.getValores());
    }//GEN-LAST:event_jbt_05ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        c.digiteNumero(2);
        jtxt_resultado.setText(c.getValores());
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jbt_00ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_00ActionPerformed
        c.digiteNumero(0);
        jtxt_resultado.setText(c.getValores());
    }//GEN-LAST:event_jbt_00ActionPerformed

    private void jbt_01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_01ActionPerformed
        c.digiteNumero(1);
        jtxt_resultado.setText(c.getValores());


    }//GEN-LAST:event_jbt_01ActionPerformed

    private void jbt_resultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_resultadoActionPerformed
        // RESULTADO
        jtxt_resultado.setText("" + c.calculo(jtxt_resultado.getText()));

    }//GEN-LAST:event_jbt_resultadoActionPerformed

    private void jbt_somarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_somarActionPerformed
        // SOMA
        c.somar(jtxt_resultado.getText());
        jtxt_resultado.setText("");

    }//GEN-LAST:event_jbt_somarActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        c.digiteNumero(3);
        jtxt_resultado.setText(c.getValores());
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jbt_04ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_04ActionPerformed
        c.digiteNumero(4);
        jtxt_resultado.setText(c.getValores());
    }//GEN-LAST:event_jbt_04ActionPerformed

    private void jbt_06ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_06ActionPerformed
        c.digiteNumero(6);
        jtxt_resultado.setText(c.getValores());
    }//GEN-LAST:event_jbt_06ActionPerformed

    private void jbt_07ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_07ActionPerformed
        c.digiteNumero(7);
        jtxt_resultado.setText(c.getValores());
    }//GEN-LAST:event_jbt_07ActionPerformed

    private void jbt_09ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_09ActionPerformed
        c.digiteNumero(9);
        jtxt_resultado.setText(c.getValores());
    }//GEN-LAST:event_jbt_09ActionPerformed

    private void jbt_limparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_limparActionPerformed
        //LIMPAR
        c.clear();
        jtxt_resultado.setText(null);
         

    }//GEN-LAST:event_jbt_limparActionPerformed

    private void jbt_subtrairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_subtrairActionPerformed
        // SUBTRACAO
        c.subtracao(jtxt_resultado.getText());
        jtxt_resultado.setText("");

    }//GEN-LAST:event_jbt_subtrairActionPerformed

    private void jbt_multiplicacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_multiplicacaoActionPerformed
        // MULTIPLICACAO
        c.multiplicacao(jtxt_resultado.getText());
        jtxt_resultado.setText("");
    }//GEN-LAST:event_jbt_multiplicacaoActionPerformed

    private void jbt_divisaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_divisaoActionPerformed
        //DIVISAO
        c.divisao(jtxt_resultado.getText());
        jtxt_resultado.setText("");

    }//GEN-LAST:event_jbt_divisaoActionPerformed

    private void jtxt_resultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_resultadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_resultadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCalculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton jbt_00;
    private javax.swing.JButton jbt_01;
    private javax.swing.JButton jbt_04;
    private javax.swing.JButton jbt_05;
    private javax.swing.JButton jbt_06;
    private javax.swing.JButton jbt_07;
    private javax.swing.JButton jbt_09;
    private javax.swing.JButton jbt_8;
    private javax.swing.JButton jbt_divisao;
    private javax.swing.JButton jbt_limpar;
    private javax.swing.JButton jbt_multiplicacao;
    private javax.swing.JButton jbt_resultado;
    private javax.swing.JButton jbt_somar;
    private javax.swing.JButton jbt_subtrair;
    private javax.swing.JTextField jtxt_resultado;
    // End of variables declaration//GEN-END:variables
}
